#!/bin/bash

mkdir motifs

cd motifs

for i in {SizeStart2..SizeEnd2..Pruning2} ; do
  if [ "$i" -lt 100 ]; then
    if [ "$i" -lt 10 ]; then
      mkdir 000$i
      cd 000$i
      cp ../../parallel_seeded_XxYy/* .
      cp ../../DATA/min000$i.xyz ./seed.in.temp
      cp -r ../../run_'SizeStart1' .
      cp -r ../../run_'SizeEnd1' .
      rm range.dat param.dat
      echo '0000 05' 000$i >> param.dat
cat > range.dat << EOF
SizeStart2 SizeEnd2 Pruning2
EOF
      ./parallel_seeded.x < /dev/null >& logfile
      for k in {1..100000..1} ; do
        a=$(ps aux | grep bh_v07 | wc | awk '{print $1}')
        if [ "$a" -lt 2 ]
          then
          break
        else
          sleep 1
        fi
      done
      ./crea
      ./analize
      ./read.x
      ./clean
      cp curve.dat ../../curve-motif-000$i.dat
      cd ..
    else
      mkdir 00$i
      cd 00$i
      cp ../../parallel_seeded_XxYy/* .
      cp ../../DATA/min00$i.xyz ./seed.in.temp
      rm range.dat param.dat
      cp -r ../../run_'SizeStart1' .
      cp -r ../../run_'SizeEnd1' .
      echo '0000 05' 00$i >> param.dat
cat > range.dat << EOF
SizeStart2 SizeEnd2 Pruning2
EOF
      ./parallel_seeded.x < /dev/null >& logfile
      for k in {1..100000..1} ; do
        a=$(ps aux | grep bh_v07 | wc | awk '{print $1}')
        if [ "$a" -lt 2 ]
          then
          break
        else
          sleep 1
        fi
      done
      ./crea
      ./analize
      ./read.x
      ./clean
      cp curve.dat ../../curve-motif-00$i.dat
      cd ..
    fi
  else
    if [ "$i" -lt 1000 ]; then
      mkdir 0$i
      cd 0$i
      cp ../../parallel_seeded_XxYy/* .
      cp ../../DATA/min0$i.xyz ./seed.in.temp 
      rm range.dat param.dat
      cp -r ../../run_'SizeStart1' .
      cp -r ../../run_'SizeEnd1' .
      echo '0000 05' 0$i >> param.dat
cat > range.dat << EOF
SizeStart2 SizeEnd2 Pruning2
EOF
      ./parallel_seeded.x < /dev/null >& logfile
      for k in {1..100000..1} ; do
        a=$(ps aux | grep bh_v07 | wc | awk '{print $1}')
        if [ "$a" -lt 2 ]
          then
          break
        else
          sleep 1
        fi
      done
      ./crea
      ./analize
      ./read.x
      ./clean
      cp curve.dat ../../curve-motif-0$i.dat
      cd ..
    fi
    if [ "$i" -lt 10000 ]; then
      mkdir $i
      cd $i
      cp ../../parallel_seeded_XxYy/* .
      cp ../../DATA/min$i.xyz ./seed.in.temp 
      rm range.dat param.dat
      cp -r ../../run_'SizeStart1' .
      cp -r ../../run_'SizeEnd1' .
      echo '0000 05' 0$i >> param.dat
cat > range.dat << EOF
SizeStart2 SizeEnd2 Pruning2
EOF
      ./parallel_seeded.x < /dev/null >& logfile
      for k in {1..100000..1} ; do
        a=$(ps aux | grep bh_v07 | wc | awk '{print $1}')
        if [ "$a" -lt 2 ]
          then
          break
        else
          sleep 1
        fi
      done
      ./crea
      ./analize
      ./read.x
      ./clean
      cp curve.dat ../../curve-motif-$i.dat
      cd ..
    fi
  fi
done
