#!/bin/bash
rm ./run_0000/bh_v07
gzip ./run_0000/ener_oparameter.out
rm ./run_0000/glo0*
for i in {Zz1..Zz2..Pruning1} ; do
rm ./run_00$i/bh_v07
gzip ./run_00$i/ener_oparameter.out
rm ./run_00$i/glo0*
done
for i in {Zz3..SizeEnd1..Pruning1} ; do
rm ./run_0$i/bh_v07
gzip ./run_0$i/ener_oparameter.out
rm ./run_0$i/glo0*
done
