#!/bin/bash
touch ./run_0000/min0100.xyz
for i in {1..9..1} ; do
touch ./run_000$i/min0100.xyz
done
for i in {10..99..1} ; do
touch ./run_00$i/min0100.xyz
done
for i in {100..SizeEnd1..1} ; do
touch ./run_0$i/min0100.xyz
done
