#!/bin/bash
for i in {SizeStart2..Zz2..Pruning2} ; do
rm ./run_00$i/bh_v07
gzip ./run_00$i/ener_oparameter.out
rm ./run_00$i/glo0*
done
for i in {Zz3..SizeEnd2..Pruning2} ; do
rm ./run_0$i/bh_v07
gzip ./run_0$i/ener_oparameter.out
rm ./run_0$i/glo0*
done
